package org.example.sintesis;

// Diccionario bilingüe inglés↔español.
// Cada palabra tiene una traducción fija (Opción A).
// Soporta ambas direcciones: EN→ES y ES→EN.

import java.util.HashMap;
import java.util.Map;

public class Diccionario {

    private Map<String, String> enEs;
    private Map<String, String> esEn;

    public Diccionario() {
        enEs = new HashMap<>();
        esEn = new HashMap<>();
        cargarEnEs();
        cargarEsEn();
    }

    private void cargarEnEs() {
        // Artículos
        enEs.put("the","el"); enEs.put("a","un"); enEs.put("an","un");
        // Pronombres
        enEs.put("i","yo"); enEs.put("you","tú"); enEs.put("he","él");
        enEs.put("she","ella"); enEs.put("it","eso"); enEs.put("we","nosotros");
        enEs.put("they","ellos"); enEs.put("me","me"); enEs.put("him","lo");
        enEs.put("her","la"); enEs.put("us","nos"); enEs.put("them","los");
        // Posesivos
        enEs.put("my","mi"); enEs.put("your","tu"); enEs.put("his","su");
        enEs.put("its","su"); enEs.put("our","nuestro"); enEs.put("their","su");
        // Demostrativos
        enEs.put("this","este"); enEs.put("that","ese");
        enEs.put("these","estos"); enEs.put("those","esos");
        // Verbos auxiliares
        enEs.put("is","es"); enEs.put("are","son"); enEs.put("was","era");
        enEs.put("were","eran"); enEs.put("be","ser"); enEs.put("been","sido");
        enEs.put("am","soy"); enEs.put("have","tengo"); enEs.put("has","tiene");
        enEs.put("had","tenía"); enEs.put("do","hago"); enEs.put("does","hace");
        enEs.put("did","hizo"); enEs.put("will","va a"); enEs.put("would","podría");
        enEs.put("can","puede"); enEs.put("could","podría"); enEs.put("should","debería");
        enEs.put("must","debe"); enEs.put("may","puede"); enEs.put("might","podría");
        // Verbos comunes
        enEs.put("run","correr"); enEs.put("runs","corre"); enEs.put("ran","corrió");
        enEs.put("eat","comer"); enEs.put("eats","come"); enEs.put("ate","comió");
        enEs.put("go","ir"); enEs.put("goes","va"); enEs.put("went","fue");
        enEs.put("see","ver"); enEs.put("sees","ve"); enEs.put("saw","vio");
        enEs.put("come","venir"); enEs.put("comes","viene"); enEs.put("came","vino");
        enEs.put("know","saber"); enEs.put("knows","sabe"); enEs.put("knew","supo");
        enEs.put("think","pensar"); enEs.put("thinks","piensa"); enEs.put("thought","pensó");
        enEs.put("like","gustar"); enEs.put("likes","gusta"); enEs.put("liked","gustó");
        enEs.put("want","querer"); enEs.put("wants","quiere"); enEs.put("wanted","quería");
        enEs.put("need","necesitar"); enEs.put("needs","necesita"); enEs.put("needed","necesitaba");
        enEs.put("love","amar"); enEs.put("loves","ama"); enEs.put("loved","amó");
        enEs.put("feel","sentir"); enEs.put("feels","siente"); enEs.put("felt","sintió");
        enEs.put("read","leer"); enEs.put("reads","lee");
        enEs.put("write","escribir"); enEs.put("writes","escribe"); enEs.put("wrote","escribió");
        enEs.put("speak","hablar"); enEs.put("speaks","habla"); enEs.put("spoke","habló");
        enEs.put("listen","escuchar"); enEs.put("listens","escucha");
        enEs.put("work","trabajar"); enEs.put("works","trabaja"); enEs.put("worked","trabajó");
        enEs.put("play","jugar"); enEs.put("plays","juega"); enEs.put("played","jugó");
        enEs.put("study","estudiar"); enEs.put("studies","estudia"); enEs.put("studied","estudió");
        enEs.put("learn","aprender"); enEs.put("learns","aprende"); enEs.put("learned","aprendió");
        enEs.put("teach","enseñar"); enEs.put("teaches","enseña"); enEs.put("taught","enseñó");
        enEs.put("help","ayudar"); enEs.put("helps","ayuda"); enEs.put("helped","ayudó");
        enEs.put("make","hacer"); enEs.put("makes","hace"); enEs.put("made","hizo");
        enEs.put("take","tomar"); enEs.put("takes","toma"); enEs.put("took","tomó");
        enEs.put("give","dar"); enEs.put("gives","da"); enEs.put("gave","dio");
        enEs.put("get","obtener"); enEs.put("gets","obtiene"); enEs.put("got","obtuvo");
        enEs.put("find","encontrar"); enEs.put("finds","encuentra"); enEs.put("found","encontró");
        enEs.put("keep","mantener"); enEs.put("keeps","mantiene"); enEs.put("kept","mantuvo");
        enEs.put("start","empezar"); enEs.put("starts","empieza"); enEs.put("started","empezó");
        enEs.put("stop","detener"); enEs.put("stops","detiene"); enEs.put("stopped","detuvo");
        enEs.put("open","abrir"); enEs.put("opens","abre"); enEs.put("opened","abrió");
        enEs.put("close","cerrar"); enEs.put("closes","cierra"); enEs.put("closed","cerró");
        enEs.put("call","llamar"); enEs.put("calls","llama"); enEs.put("called","llamó");
        enEs.put("try","intentar"); enEs.put("tries","intenta"); enEs.put("tried","intentó");
        enEs.put("use","usar"); enEs.put("uses","usa"); enEs.put("used","usó");
        enEs.put("show","mostrar"); enEs.put("shows","muestra"); enEs.put("showed","mostró");
        enEs.put("walk","caminar"); enEs.put("walks","camina"); enEs.put("walked","caminó");
        enEs.put("talk","hablar"); enEs.put("talks","habla"); enEs.put("talked","habló");
        enEs.put("live","vivir"); enEs.put("lives","vive"); enEs.put("lived","vivió");
        enEs.put("sleep","dormir"); enEs.put("sleeps","duerme"); enEs.put("slept","durmió");
        enEs.put("buy","comprar"); enEs.put("buys","compra"); enEs.put("bought","compró");
        enEs.put("sell","vender"); enEs.put("sells","vende"); enEs.put("sold","vendió");
        enEs.put("win","ganar"); enEs.put("wins","gana"); enEs.put("won","ganó");
        enEs.put("lose","perder"); enEs.put("loses","pierde"); enEs.put("lost","perdió");
        enEs.put("sing","cantar"); enEs.put("sings","canta"); enEs.put("sang","cantó");
        enEs.put("dance","bailar"); enEs.put("dances","baila"); enEs.put("danced","bailó");
        enEs.put("cook","cocinar"); enEs.put("cooks","cocina"); enEs.put("cooked","cocinó");
        enEs.put("wait","esperar"); enEs.put("waits","espera"); enEs.put("waited","esperó");
        enEs.put("ask","preguntar"); enEs.put("asks","pregunta"); enEs.put("asked","preguntó");
        enEs.put("answer","responder"); enEs.put("answers","responde"); enEs.put("answered","respondió");
        enEs.put("move","mover"); enEs.put("moves","mueve"); enEs.put("moved","movió");
        enEs.put("bring","traer"); enEs.put("brings","trae"); enEs.put("brought","trajo");
        enEs.put("say","decir"); enEs.put("says","dice"); enEs.put("said","dijo");
        enEs.put("tell","contar"); enEs.put("tells","cuenta"); enEs.put("told","contó");
        enEs.put("put","poner"); enEs.put("puts","pone");
        enEs.put("draw","dibujar"); enEs.put("draws","dibuja"); enEs.put("drew","dibujó");
        enEs.put("create","crear"); enEs.put("creates","crea"); enEs.put("created","creó");
        enEs.put("fly","volar"); enEs.put("flies","vuela"); enEs.put("flew","voló");
        enEs.put("swim","nadar"); enEs.put("swims","nada"); enEs.put("swam","nadó");
        enEs.put("drive","conducir"); enEs.put("drives","conduce"); enEs.put("drove","condujo");
        // Sustantivos
        enEs.put("cat","gato"); enEs.put("cats","gatos");
        enEs.put("dog","perro"); enEs.put("dogs","perros");
        enEs.put("house","casa"); enEs.put("houses","casas");
        enEs.put("car","carro"); enEs.put("cars","carros");
        enEs.put("book","libro"); enEs.put("books","libros");
        enEs.put("man","hombre"); enEs.put("men","hombres");
        enEs.put("woman","mujer"); enEs.put("women","mujeres");
        enEs.put("child","niño"); enEs.put("children","niños");
        enEs.put("boy","chico"); enEs.put("boys","chicos");
        enEs.put("girl","chica"); enEs.put("girls","chicas");
        enEs.put("baby","bebé"); enEs.put("babies","bebés");
        enEs.put("day","día"); enEs.put("days","días");
        enEs.put("year","año"); enEs.put("years","años");
        enEs.put("time","tiempo"); enEs.put("life","vida");
        enEs.put("world","mundo"); enEs.put("school","escuela");
        enEs.put("schools","escuelas"); enEs.put("work","trabajo");
        enEs.put("water","agua"); enEs.put("food","comida");
        enEs.put("city","ciudad"); enEs.put("cities","ciudades");
        enEs.put("country","país"); enEs.put("countries","países");
        enEs.put("family","familia"); enEs.put("families","familias");
        enEs.put("friend","amigo"); enEs.put("friends","amigos");
        enEs.put("hand","mano"); enEs.put("hands","manos");
        enEs.put("eye","ojo"); enEs.put("eyes","ojos");
        enEs.put("face","cara"); enEs.put("head","cabeza");
        enEs.put("door","puerta"); enEs.put("doors","puertas");
        enEs.put("table","mesa"); enEs.put("tables","mesas");
        enEs.put("chair","silla"); enEs.put("chairs","sillas");
        enEs.put("room","habitación"); enEs.put("rooms","habitaciones");
        enEs.put("tree","árbol"); enEs.put("trees","árboles");
        enEs.put("flower","flor"); enEs.put("flowers","flores");
        enEs.put("bird","pájaro"); enEs.put("birds","pájaros");
        enEs.put("sun","sol"); enEs.put("moon","luna");
        enEs.put("star","estrella"); enEs.put("stars","estrellas");
        enEs.put("sky","cielo"); enEs.put("street","calle"); enEs.put("streets","calles");
        enEs.put("name","nombre"); enEs.put("names","nombres");
        enEs.put("word","palabra"); enEs.put("words","palabras");
        enEs.put("language","idioma"); enEs.put("morning","mañana");
        enEs.put("afternoon","tarde"); enEs.put("night","noche");
        enEs.put("week","semana"); enEs.put("weeks","semanas");
        enEs.put("month","mes"); enEs.put("months","meses");
        enEs.put("money","dinero"); enEs.put("road","camino");
        enEs.put("heart","corazón"); enEs.put("mind","mente");
        enEs.put("body","cuerpo"); enEs.put("voice","voz");
        enEs.put("story","historia"); enEs.put("stories","historias");
        enEs.put("question","pregunta"); enEs.put("questions","preguntas");
        enEs.put("problem","problema"); enEs.put("problems","problemas");
        enEs.put("idea","idea"); enEs.put("ideas","ideas");
        enEs.put("teacher","maestro"); enEs.put("teachers","maestros");
        enEs.put("student","estudiante"); enEs.put("students","estudiantes");
        enEs.put("doctor","doctor"); enEs.put("doctors","doctores");
        enEs.put("mother","madre"); enEs.put("father","padre");
        enEs.put("son","hijo"); enEs.put("sons","hijos");
        enEs.put("daughter","hija"); enEs.put("daughters","hijas");
        enEs.put("brother","hermano"); enEs.put("brothers","hermanos");
        enEs.put("sister","hermana"); enEs.put("sisters","hermanas");
        enEs.put("people","gente"); enEs.put("person","persona");
        enEs.put("place","lugar"); enEs.put("places","lugares");
        enEs.put("thing","cosa"); enEs.put("things","cosas");
        enEs.put("park","parque"); enEs.put("parks","parques");
        enEs.put("computer","computadora"); enEs.put("phone","teléfono");
        enEs.put("music","música"); enEs.put("game","juego"); enEs.put("games","juegos");
        enEs.put("sport","deporte"); enEs.put("sports","deportes");
        enEs.put("apple","manzana"); enEs.put("apples","manzanas");
        enEs.put("bread","pan"); enEs.put("milk","leche");
        enEs.put("egg","huevo"); enEs.put("eggs","huevos");
        enEs.put("fruit","fruta"); enEs.put("number","número");
        enEs.put("color","color"); enEs.put("light","luz");
        enEs.put("river","río"); enEs.put("sea","mar"); enEs.put("ocean","océano");
        enEs.put("mountain","montaña"); enEs.put("garden","jardín");
        enEs.put("building","edificio"); enEs.put("window","ventana");
        enEs.put("floor","piso"); enEs.put("paper","papel");
        enEs.put("pen","pluma"); enEs.put("pencil","lápiz");
        // Adjetivos
        enEs.put("good","bueno"); enEs.put("bad","malo");
        enEs.put("big","grande"); enEs.put("small","pequeño");
        enEs.put("tall","alto"); enEs.put("short","bajo");
        enEs.put("long","largo"); enEs.put("new","nuevo"); enEs.put("old","viejo");
        enEs.put("young","joven"); enEs.put("beautiful","hermoso");
        enEs.put("ugly","feo"); enEs.put("happy","feliz"); enEs.put("sad","triste");
        enEs.put("fast","rápido"); enEs.put("slow","lento");
        enEs.put("hot","caliente"); enEs.put("cold","frío");
        enEs.put("warm","cálido"); enEs.put("cool","fresco");
        enEs.put("white","blanco"); enEs.put("black","negro");
        enEs.put("red","rojo"); enEs.put("blue","azul");
        enEs.put("green","verde"); enEs.put("yellow","amarillo");
        enEs.put("strong","fuerte"); enEs.put("weak","débil");
        enEs.put("hard","duro"); enEs.put("easy","fácil");
        enEs.put("rich","rico"); enEs.put("poor","pobre");
        enEs.put("clean","limpio"); enEs.put("dirty","sucio");
        enEs.put("full","lleno"); enEs.put("empty","vacío");
        enEs.put("important","importante"); enEs.put("special","especial");
        enEs.put("great","genial"); enEs.put("little","pequeño");
        enEs.put("kind","amable"); enEs.put("brave","valiente");
        enEs.put("funny","gracioso"); enEs.put("smart","inteligente");
        enEs.put("first","primero"); enEs.put("last","último");
        enEs.put("next","siguiente"); enEs.put("other","otro");
        enEs.put("same","mismo"); enEs.put("real","real");
        enEs.put("possible","posible"); enEs.put("different","diferente");
        enEs.put("simple","simple"); enEs.put("true","verdadero");
        // Adverbios
        enEs.put("very","muy"); enEs.put("well","bien");
        enEs.put("also","también"); enEs.put("just","solo");
        enEs.put("now","ahora"); enEs.put("then","entonces");
        enEs.put("here","aquí"); enEs.put("there","allí");
        enEs.put("always","siempre"); enEs.put("never","nunca");
        enEs.put("sometimes","a veces"); enEs.put("still","todavía");
        enEs.put("already","ya"); enEs.put("soon","pronto");
        enEs.put("again","otra vez"); enEs.put("quite","bastante");
        enEs.put("much","mucho"); enEs.put("more","más"); enEs.put("less","menos");
        enEs.put("really","realmente"); enEs.put("quickly","rápidamente");
        enEs.put("slowly","lentamente"); enEs.put("early","temprano");
        enEs.put("late","tarde"); enEs.put("together","juntos");
        enEs.put("perhaps","quizás"); enEs.put("maybe","tal vez");
        enEs.put("almost","casi"); enEs.put("yesterday","ayer");
        enEs.put("today","hoy"); enEs.put("tomorrow","mañana");
        // Preposiciones
        enEs.put("in","en"); enEs.put("on","sobre"); enEs.put("at","en");
        enEs.put("to","a"); enEs.put("for","para"); enEs.put("of","de");
        enEs.put("with","con"); enEs.put("by","por"); enEs.put("from","desde");
        enEs.put("about","sobre"); enEs.put("before","antes de");
        enEs.put("after","después de"); enEs.put("between","entre");
        enEs.put("under","bajo"); enEs.put("over","sobre");
        enEs.put("near","cerca de"); enEs.put("behind","detrás de");
        enEs.put("without","sin"); enEs.put("during","durante");
        enEs.put("since","desde"); enEs.put("until","hasta");
        enEs.put("toward","hacia"); enEs.put("into","dentro de");
        enEs.put("through","a través de"); enEs.put("above","encima de");
        enEs.put("below","debajo de"); enEs.put("beside","al lado de");
        // Conjunciones
        enEs.put("and","y"); enEs.put("but","pero"); enEs.put("or","o");
        enEs.put("nor","ni"); enEs.put("so","así que"); enEs.put("yet","sin embargo");
        enEs.put("because","porque"); enEs.put("if","si");
        enEs.put("although","aunque"); enEs.put("though","aunque");
        enEs.put("when","cuando"); enEs.put("where","donde");
        enEs.put("while","mientras"); enEs.put("that","que");
        enEs.put("which","cual"); enEs.put("who","quien");
        enEs.put("than","que"); enEs.put("as","como");
        // Puntuación
        enEs.put(".",".");enEs.put(",",",");enEs.put("!","!");
        enEs.put("?","?");enEs.put(";",";");enEs.put(":",":");
    }

    private void cargarEsEn() {
        // Artículos
        esEn.put("el","the"); esEn.put("la","the"); esEn.put("los","the");
        esEn.put("las","the"); esEn.put("un","a"); esEn.put("una","a");
        esEn.put("unos","some"); esEn.put("unas","some"); esEn.put("lo","the");
        // Pronombres
        esEn.put("yo","I"); esEn.put("tú","you"); esEn.put("él","he");
        esEn.put("ella","she"); esEn.put("nosotros","we"); esEn.put("nosotras","we");
        esEn.put("ellos","they"); esEn.put("ellas","they");
        esEn.put("me","me"); esEn.put("te","you"); esEn.put("se","himself");
        esEn.put("nos","us"); esEn.put("le","him"); esEn.put("les","them");
        // Posesivos
        esEn.put("mi","my"); esEn.put("mis","my"); esEn.put("tu","your");
        esEn.put("tus","your"); esEn.put("su","his"); esEn.put("sus","his");
        esEn.put("nuestro","our"); esEn.put("nuestra","our");
        esEn.put("nuestros","our"); esEn.put("nuestras","our");
        // Demostrativos
        esEn.put("este","this"); esEn.put("esta","this");
        esEn.put("estos","these"); esEn.put("estas","these");
        esEn.put("ese","that"); esEn.put("esa","that");
        esEn.put("esos","those"); esEn.put("esas","those");
        esEn.put("aquel","that"); esEn.put("aquella","that");
        // Verbos
        esEn.put("es","is"); esEn.put("son","are"); esEn.put("era","was");
        esEn.put("eran","were"); esEn.put("ser","to be"); esEn.put("sido","been");
        esEn.put("estar","to be"); esEn.put("estoy","am"); esEn.put("estás","are");
        esEn.put("está","is"); esEn.put("estamos","are"); esEn.put("están","are");
        esEn.put("estuvo","was"); esEn.put("estuvieron","were");
        esEn.put("fue","was"); esEn.put("fueron","were");
        esEn.put("tengo","have"); esEn.put("tienes","have"); esEn.put("tiene","has");
        esEn.put("tenemos","have"); esEn.put("tienen","have"); esEn.put("tener","to have");
        esEn.put("voy","go"); esEn.put("vas","go"); esEn.put("va","goes");
        esEn.put("vamos","go"); esEn.put("van","go"); esEn.put("ir","to go");
        esEn.put("corro","run"); esEn.put("corres","run"); esEn.put("corre","runs");
        esEn.put("corremos","run"); esEn.put("corren","run"); esEn.put("corrió","ran");
        esEn.put("como","eat"); esEn.put("comes","eat"); esEn.put("come","eats");
        esEn.put("comemos","eat"); esEn.put("comen","eat"); esEn.put("comió","ate");
        esEn.put("hablo","speak"); esEn.put("hablas","speak"); esEn.put("habla","speaks");
        esEn.put("hablamos","speak"); esEn.put("hablan","speak"); esEn.put("habló","spoke");
        esEn.put("trabajo","work"); esEn.put("trabajas","work"); esEn.put("trabaja","works");
        esEn.put("trabajamos","work"); esEn.put("trabajan","work"); esEn.put("trabajó","worked");
        esEn.put("estudio","study"); esEn.put("estudias","study"); esEn.put("estudia","studies");
        esEn.put("estudiamos","study"); esEn.put("estudian","study"); esEn.put("estudió","studied");
        esEn.put("vivo","live"); esEn.put("vives","live"); esEn.put("vive","lives");
        esEn.put("vivimos","live"); esEn.put("viven","live"); esEn.put("vivió","lived");
        esEn.put("ayudo","help"); esEn.put("ayudas","help"); esEn.put("ayuda","helps");
        esEn.put("ayudamos","help"); esEn.put("ayudan","help"); esEn.put("ayudó","helped");
        esEn.put("necesito","need"); esEn.put("necesitas","need"); esEn.put("necesita","needs");
        esEn.put("necesitamos","need"); esEn.put("necesitan","need");
        esEn.put("quiero","want"); esEn.put("quieres","want"); esEn.put("quiere","wants");
        esEn.put("queremos","want"); esEn.put("quieren","want"); esEn.put("quiso","wanted");
        esEn.put("pienso","think"); esEn.put("piensas","think"); esEn.put("piensa","thinks");
        esEn.put("pensamos","think"); esEn.put("piensan","think"); esEn.put("pensó","thought");
        esEn.put("siento","feel"); esEn.put("sientes","feel"); esEn.put("siente","feels");
        esEn.put("sentimos","feel"); esEn.put("sienten","feel"); esEn.put("sintió","felt");
        esEn.put("camino","walk"); esEn.put("caminas","walk"); esEn.put("camina","walks");
        esEn.put("caminamos","walk"); esEn.put("caminan","walk"); esEn.put("caminó","walked");
        esEn.put("leo","read"); esEn.put("lees","read"); esEn.put("lee","reads");
        esEn.put("leemos","read"); esEn.put("leen","read"); esEn.put("leyó","read");
        esEn.put("escribo","write"); esEn.put("escribes","write"); esEn.put("escribe","writes");
        esEn.put("escribimos","write"); esEn.put("escriben","write"); esEn.put("escribió","wrote");
        esEn.put("llamo","call"); esEn.put("llamas","call"); esEn.put("llama","calls");
        esEn.put("llamamos","call"); esEn.put("llaman","call"); esEn.put("llamó","called");
        esEn.put("abro","open"); esEn.put("abres","open"); esEn.put("abre","opens");
        esEn.put("abrimos","open"); esEn.put("abren","open"); esEn.put("abrió","opened");
        esEn.put("cierro","close"); esEn.put("cierras","close"); esEn.put("cierra","closes");
        esEn.put("cerramos","close"); esEn.put("cierran","close"); esEn.put("cerró","closed");
        esEn.put("canto","sing"); esEn.put("cantas","sing"); esEn.put("canta","sings");
        esEn.put("cantamos","sing"); esEn.put("cantan","sing"); esEn.put("cantó","sang");
        esEn.put("bailo","dance"); esEn.put("bailas","dance"); esEn.put("baila","dances");
        esEn.put("bailamos","dance"); esEn.put("bailan","dance"); esEn.put("bailó","danced");
        esEn.put("cocino","cook"); esEn.put("cocinas","cook"); esEn.put("cocina","cooks");
        esEn.put("cocinamos","cook"); esEn.put("cocinan","cook"); esEn.put("cocinó","cooked");
        esEn.put("compro","buy"); esEn.put("compras","buy"); esEn.put("compra","buys");
        esEn.put("compramos","buy"); esEn.put("compran","buy"); esEn.put("compró","bought");
        esEn.put("duermo","sleep"); esEn.put("duermes","sleep"); esEn.put("duerme","sleeps");
        esEn.put("dormimos","sleep"); esEn.put("duermen","sleep"); esEn.put("durmió","slept");
        // Sustantivos
        esEn.put("gato","cat"); esEn.put("gatos","cats");
        esEn.put("perro","dog"); esEn.put("perros","dogs");
        esEn.put("casa","house"); esEn.put("casas","houses");
        esEn.put("carro","car"); esEn.put("carros","cars");
        esEn.put("coche","car"); esEn.put("coches","cars");
        esEn.put("libro","book"); esEn.put("libros","books");
        esEn.put("hombre","man"); esEn.put("hombres","men");
        esEn.put("mujer","woman"); esEn.put("mujeres","women");
        esEn.put("niño","boy"); esEn.put("niños","boys");
        esEn.put("niña","girl"); esEn.put("niñas","girls");
        esEn.put("bebé","baby"); esEn.put("bebés","babies");
        esEn.put("día","day"); esEn.put("días","days");
        esEn.put("año","year"); esEn.put("años","years");
        esEn.put("tiempo","time"); esEn.put("vida","life");
        esEn.put("mundo","world"); esEn.put("escuela","school");
        esEn.put("escuelas","schools"); esEn.put("agua","water");
        esEn.put("comida","food"); esEn.put("ciudad","city");
        esEn.put("ciudades","cities"); esEn.put("país","country");
        esEn.put("países","countries"); esEn.put("familia","family");
        esEn.put("familias","families"); esEn.put("amigo","friend");
        esEn.put("amigos","friends"); esEn.put("amiga","friend");
        esEn.put("amigas","friends"); esEn.put("mano","hand");
        esEn.put("manos","hands"); esEn.put("ojo","eye"); esEn.put("ojos","eyes");
        esEn.put("cara","face"); esEn.put("cabeza","head");
        esEn.put("puerta","door"); esEn.put("puertas","doors");
        esEn.put("mesa","table"); esEn.put("mesas","tables");
        esEn.put("silla","chair"); esEn.put("sillas","chairs");
        esEn.put("árbol","tree"); esEn.put("árboles","trees");
        esEn.put("flor","flower"); esEn.put("flores","flowers");
        esEn.put("pájaro","bird"); esEn.put("pájaros","birds");
        esEn.put("sol","sun"); esEn.put("luna","moon");
        esEn.put("estrella","star"); esEn.put("estrellas","stars");
        esEn.put("cielo","sky"); esEn.put("calle","street"); esEn.put("calles","streets");
        esEn.put("nombre","name"); esEn.put("nombres","names");
        esEn.put("palabra","word"); esEn.put("palabras","words");
        esEn.put("idioma","language"); esEn.put("noche","night");
        esEn.put("semana","week"); esEn.put("semanas","weeks");
        esEn.put("mes","month"); esEn.put("meses","months");
        esEn.put("dinero","money"); esEn.put("corazón","heart");
        esEn.put("mente","mind"); esEn.put("cuerpo","body"); esEn.put("voz","voice");
        esEn.put("historia","story"); esEn.put("historias","stories");
        esEn.put("pregunta","question"); esEn.put("preguntas","questions");
        esEn.put("problema","problem"); esEn.put("problemas","problems");
        esEn.put("idea","idea"); esEn.put("ideas","ideas");
        esEn.put("maestro","teacher"); esEn.put("maestros","teachers");
        esEn.put("maestra","teacher"); esEn.put("maestras","teachers");
        esEn.put("estudiante","student"); esEn.put("estudiantes","students");
        esEn.put("doctor","doctor"); esEn.put("doctores","doctors");
        esEn.put("madre","mother"); esEn.put("padre","father");
        esEn.put("hijo","son"); esEn.put("hijos","sons");
        esEn.put("hija","daughter"); esEn.put("hijas","daughters");
        esEn.put("hermano","brother"); esEn.put("hermanos","brothers");
        esEn.put("hermana","sister"); esEn.put("hermanas","sisters");
        esEn.put("gente","people"); esEn.put("persona","person");
        esEn.put("personas","persons"); esEn.put("lugar","place");
        esEn.put("lugares","places"); esEn.put("cosa","thing");
        esEn.put("cosas","things"); esEn.put("parque","park");
        esEn.put("parques","parks"); esEn.put("computadora","computer");
        esEn.put("teléfono","phone"); esEn.put("teléfonos","phones");
        esEn.put("música","music"); esEn.put("juego","game"); esEn.put("juegos","games");
        esEn.put("deporte","sport"); esEn.put("deportes","sports");
        esEn.put("manzana","apple"); esEn.put("manzanas","apples");
        esEn.put("pan","bread"); esEn.put("leche","milk");
        esEn.put("huevo","egg"); esEn.put("huevos","eggs");
        esEn.put("fruta","fruit"); esEn.put("frutas","fruits");
        esEn.put("número","number"); esEn.put("números","numbers");
        esEn.put("color","color"); esEn.put("colores","colors");
        esEn.put("luz","light"); esEn.put("río","river"); esEn.put("ríos","rivers");
        esEn.put("mar","sea"); esEn.put("océano","ocean");
        esEn.put("montaña","mountain"); esEn.put("montañas","mountains");
        esEn.put("jardín","garden"); esEn.put("jardines","gardens");
        esEn.put("edificio","building"); esEn.put("edificios","buildings");
        esEn.put("ventana","window"); esEn.put("ventanas","windows");
        esEn.put("piso","floor"); esEn.put("papel","paper");
        esEn.put("pluma","pen"); esEn.put("plumas","pens");
        esEn.put("lápiz","pencil"); esEn.put("lápices","pencils");
        // Adjetivos
        esEn.put("bueno","good"); esEn.put("buena","good");
        esEn.put("malo","bad"); esEn.put("mala","bad");
        esEn.put("grande","big"); esEn.put("pequeño","small"); esEn.put("pequeña","small");
        esEn.put("alto","tall"); esEn.put("alta","tall");
        esEn.put("bajo","short"); esEn.put("baja","short");
        esEn.put("largo","long"); esEn.put("larga","long");
        esEn.put("nuevo","new"); esEn.put("nueva","new");
        esEn.put("viejo","old"); esEn.put("vieja","old");
        esEn.put("joven","young"); esEn.put("hermoso","beautiful"); esEn.put("hermosa","beautiful");
        esEn.put("bonito","pretty"); esEn.put("bonita","pretty");
        esEn.put("feo","ugly"); esEn.put("fea","ugly");
        esEn.put("feliz","happy"); esEn.put("triste","sad");
        esEn.put("rápido","fast"); esEn.put("rápida","fast");
        esEn.put("lento","slow"); esEn.put("lenta","slow");
        esEn.put("caliente","hot"); esEn.put("frío","cold"); esEn.put("fría","cold");
        esEn.put("cálido","warm"); esEn.put("cálida","warm");
        esEn.put("fresco","cool"); esEn.put("fresca","cool");
        esEn.put("blanco","white"); esEn.put("blanca","white");
        esEn.put("negro","black"); esEn.put("negra","black");
        esEn.put("rojo","red"); esEn.put("roja","red");
        esEn.put("azul","blue"); esEn.put("verde","green");
        esEn.put("amarillo","yellow"); esEn.put("amarilla","yellow");
        esEn.put("fuerte","strong"); esEn.put("débil","weak");
        esEn.put("fácil","easy"); esEn.put("difícil","hard");
        esEn.put("rico","rich"); esEn.put("rica","rich");
        esEn.put("pobre","poor"); esEn.put("limpio","clean"); esEn.put("limpia","clean");
        esEn.put("sucio","dirty"); esEn.put("sucia","dirty");
        esEn.put("lleno","full"); esEn.put("llena","full");
        esEn.put("vacío","empty"); esEn.put("vacía","empty");
        esEn.put("importante","important"); esEn.put("especial","special");
        esEn.put("inteligente","smart"); esEn.put("amable","kind");
        esEn.put("valiente","brave"); esEn.put("gracioso","funny"); esEn.put("graciosa","funny");
        esEn.put("serio","serious"); esEn.put("seria","serious");
        esEn.put("primero","first"); esEn.put("primera","first");
        esEn.put("último","last"); esEn.put("última","last");
        esEn.put("siguiente","next"); esEn.put("otro","other"); esEn.put("otra","other");
        esEn.put("mismo","same"); esEn.put("misma","same");
        esEn.put("posible","possible"); esEn.put("diferente","different");
        esEn.put("simple","simple"); esEn.put("real","real");
        esEn.put("verdadero","true"); esEn.put("verdadera","true");
        // Adverbios
        esEn.put("muy","very"); esEn.put("bien","well");
        esEn.put("también","also"); esEn.put("solo","just");
        esEn.put("ahora","now"); esEn.put("entonces","then");
        esEn.put("aquí","here"); esEn.put("allí","there"); esEn.put("allá","there");
        esEn.put("siempre","always"); esEn.put("nunca","never");
        esEn.put("todavía","still"); esEn.put("ya","already");
        esEn.put("pronto","soon"); esEn.put("bastante","quite");
        esEn.put("mucho","much"); esEn.put("más","more"); esEn.put("menos","less");
        esEn.put("realmente","really"); esEn.put("rápidamente","quickly");
        esEn.put("lentamente","slowly"); esEn.put("temprano","early");
        esEn.put("tarde","late"); esEn.put("juntos","together");
        esEn.put("quizás","perhaps"); esEn.put("tal vez","maybe");
        esEn.put("casi","almost"); esEn.put("ayer","yesterday");
        esEn.put("hoy","today"); esEn.put("mañana","tomorrow");
        esEn.put("lejos","away"); esEn.put("atrás","back");
        // Preposiciones
        esEn.put("en","in"); esEn.put("sobre","on"); esEn.put("a","to");
        esEn.put("para","for"); esEn.put("de","of"); esEn.put("con","with");
        esEn.put("por","by"); esEn.put("desde","from"); esEn.put("hacia","toward");
        esEn.put("hasta","until"); esEn.put("entre","between");
        esEn.put("bajo","under"); esEn.put("sin","without");
        esEn.put("durante","during"); esEn.put("antes","before");
        esEn.put("después","after"); esEn.put("encima","above");
        esEn.put("debajo","below"); esEn.put("cerca","near");
        esEn.put("detrás","behind"); esEn.put("junto","beside");
        // Conjunciones
        esEn.put("y","and"); esEn.put("e","and"); esEn.put("pero","but");
        esEn.put("o","or"); esEn.put("u","or"); esEn.put("ni","nor");
        esEn.put("porque","because"); esEn.put("si","if");
        esEn.put("aunque","although"); esEn.put("cuando","when");
        esEn.put("donde","where"); esEn.put("mientras","while");
        esEn.put("que","that"); esEn.put("como","as"); esEn.put("pues","so");
        // Contracciones
        esEn.put("al","to the"); esEn.put("del","of the");
        // Puntuación
        esEn.put(".",".");esEn.put(",",",");esEn.put("!","!");
        esEn.put("?","?");esEn.put(";",";");esEn.put(":",":");
    }

    // Traduce una palabra según la dirección indicada
    public String traducir(String palabra, String direccion) {
        String p = palabra.toLowerCase();
        if (direccion.equals("en-es")) return enEs.getOrDefault(p, palabra);
        else                           return esEn.getOrDefault(p, palabra);
    }
}